---
title: RHODAN

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  tools:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: bin
